### ISSUE TITLE
Can not compile project in 2022

### ISSUE THREAD

**Issue by dorinionescu** [adrientoub/myaftereffects#1]
I tried "gradle run" with various gradle versions but each gives errors. 
How can I revive and test this project?
I tried
gradle-3.5.1
gradle-4.10.2
gradle-5.6.4
gradle-6.9.3
gradle-7.5.1

**Comment by adrientoub** [comment]
There were major changes in Gradle since this project was developed.
I updated the project to work with Gradle 7.6 in ca6b4d26b838239df3dd2dc6c497b48662c0ff60, it should work for you now.
